spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      username: admin
      password: password
      database: lab4
      repositories:
        type: auto
      authentication-database: admin
  devtools:
    restart:
      enabled: true
server:
  port: 5000
  servlet:
    context-path: /api
logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
bakhteev:
  app:
    jwtAccessSecret: accessTokenSecret
#    jwtAccessExpirationMs: 3600000 # 1 hour
#    jwtRefreshExpirationMs: 86400000 # 1 day
    jwtAccessExpirationMs: 60000
    jwtRefreshExpirationMs: 120000